on:
  pull_request:
      types: [opened, synchronize, reopened]
  push: {}
jobs:
  build-pr:
    name: "build the PR"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "DeterminateSystems/nix-installer-action@v21"
      - name: install key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Run a build...
        run: "nix run nixpkgs#nixos-rebuild build -- --flake .#jingliu --build-host gha@actions.jingliu.arvinderd.com"
